# Site settings
title: CMDdesign
email: chad.m.danford@gmail.com

collections:
- exhibitions
- ad_work
- web

talent1: profile
talent1subhead: i came, i saw, i conquered!

talent2: exhibition
talent2subhead: projects of the last few years

talent3: ad work
talent3subhead: some of the stuff i'm currently working on

talent4: web
talent4subhead: working it every day of my life

description: > # this means to ignore newlines until "baseurl:"
  Pretty much the first portfolio i've done in over 9 years.

baseurl: "/portfolio"
url: "http://cmd1209.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

cdn_path: https://dl.dropboxusercontent.com/u/947851/portfolio/

gems:
  - octopress-autoprefixer

sass:
  sass_dir: assets/stylesheets
  style: :compressed
