# Site settings
title: CMDdesign
email: chad.m.danford@gmail.com
linkedin: linkedin.com/in/chad-matthew-danford-44a82764
facebook: facebook.com/chad.danford
instagram: instagram.com/instamaticchad

collections:
  profile:
    output: true
  exhibitions:
    output: true
  ad_work:
    output: true
  web:
    output: true

defaults:
  - scope:
      type: profile
    values:
      layout: post
  - scope:
      type: exhibitions
    values:
      layout: post
  - scope:
      type: ad_work
    values:
      layout: post
  - scope:
      type: web
    values:
      layout: post

talent1: profile

talent2: exhibition

talent3: ad work

talent4: web

description: > # this means to ignore newlines until "baseurl:"
  Pretty much the first portfolio i've done in over 9 years.

baseurl: ""
url: "http://www.chadmdanford.com" # the base hostname & protocol for your site
# baseurl: "/portfolio"
# url: "http://cmd1209.github.io" # the base hostname & protocol for your site
twitter_username: Chad_M_Danford
github_username:  cmd1209

# Build settings
markdown: kramdown

cdn_path: http://www.studio-andreas-heller.de//funstuff/port/

gems:
  - octopress-autoprefixer

sass:
  sass_dir: assets/stylesheets
  style: :compressed
